- hosts: terraform-ansible
  tasks:
  - name: creating archive
    copy:
      dest: /home/ubuntu/index.html
      content: <h1>Xesquyedele</h1>
  - name: creating server
    shell: "nohup busybox httpd -f -p 8080 &"
